services:
  - name: starvnt-backend
    type: web
    env: node
    branch: main
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: "https://starvnt-frontend.vercel.app"
